# Generated by Django 4.1.6 on 2023-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
