# Generated by Django 4.1.6 on 2023-02-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_product_purchase_alter_myuser_options_return_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'verbose_name': 'Return', 'verbose_name_plural': 'Returns'},
        ),
    ]
