# Generated by Django 4.1.6 on 2023-02-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_return_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created']},
        ),
    ]
