# Generated by Django 4.1.6 on 2023-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_product_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
