# Generated by Django 4.1.6 on 2023-02-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_return_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created']},
        ),
    ]
