# Generated by Django 4.1.6 on 2023-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_rename_delete_return_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'MyUsers'},
        ),
    ]
